-- ============================================
-- week-6 paid_content — week-5 Supabase 프로젝트에 추가
-- ============================================

drop table if exists public.purchases cascade;
drop table if exists public.contents cascade;

-- ── contents ────────────────────────────────────
create table public.contents (
  id          bigint primary key generated by default as identity,
  title       text not null,
  preview     text not null,             -- 결제 전 무료 미리보기 (앞 3줄)
  body        text not null,             -- 결제 후에만 공개
  price       int  not null check (price >= 0),
  category    text,
  created_at  timestamptz not null default now()
);

alter table public.contents enable row level security;

-- 누구나 SELECT 가능 (단, body는 코드에서 별도 권한 체크)
drop policy if exists "contents_select_public" on public.contents;
create policy "contents_select_public"
  on public.contents for select
  to anon, authenticated
  using (true);

-- ── purchases ───────────────────────────────────
create table public.purchases (
  id              bigint primary key generated by default as identity,
  user_id         uuid not null references auth.users(id) on delete cascade,
  content_id      bigint not null references public.contents(id) on delete cascade,
  amount          int  not null,
  toss_payment_key text,
  toss_order_id    text unique not null,
  paid_at         timestamptz default now(),
  created_at      timestamptz not null default now(),
  unique(user_id, content_id)            -- 동일 콘텐츠 중복 결제 방지 (paid 기준)
);

alter table public.purchases enable row level security;

drop policy if exists "purchases_select_own" on public.purchases;
create policy "purchases_select_own"
  on public.purchases for select to authenticated
  using (user_id = auth.uid());

drop policy if exists "purchases_insert_own" on public.purchases;
create policy "purchases_insert_own"
  on public.purchases for insert to authenticated
  with check (user_id = auth.uid());

create index if not exists purchases_user_id_idx on public.purchases(user_id);
create index if not exists purchases_content_id_idx on public.purchases(content_id);
