-- ─────────────────────────────────────────────
-- 식물 가게 쇼핑몰 스키마
-- products: 공개 SELECT, cart: 본인만 CRUD
-- ─────────────────────────────────────────────

-- products ────────────────────────────────────
drop table if exists public.cart cascade;
drop table if exists public.products cascade;

create table public.products (
  id          bigint generated by default as identity primary key,
  name        text not null,
  price       integer not null check (price >= 0),
  image_url   text,
  description text,
  created_at  timestamptz not null default now()
);

alter table public.products enable row level security;

drop policy if exists "products_select_public" on public.products;
create policy "products_select_public"
  on public.products for select
  to anon, authenticated
  using (true);

-- cart ────────────────────────────────────────
create table public.cart (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references auth.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  quantity   integer not null default 1 check (quantity > 0),
  created_at timestamptz not null default now(),
  unique (user_id, product_id)
);

alter table public.cart enable row level security;

drop policy if exists "cart_select_own" on public.cart;
create policy "cart_select_own"
  on public.cart for select
  to authenticated
  using (user_id = auth.uid());

drop policy if exists "cart_insert_own" on public.cart;
create policy "cart_insert_own"
  on public.cart for insert
  to authenticated
  with check (user_id = auth.uid());

drop policy if exists "cart_update_own" on public.cart;
create policy "cart_update_own"
  on public.cart for update
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

drop policy if exists "cart_delete_own" on public.cart;
create policy "cart_delete_own"
  on public.cart for delete
  to authenticated
  using (user_id = auth.uid());

-- ─────────────────────────────────────────────
-- SEED: 식물 가게 샘플 상품 10개 (Unsplash 무료 이미지)
-- ─────────────────────────────────────────────
insert into public.products (name, price, image_url, description) values
  ('몬스테라 델리시오사', 38000,
   'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?w=600',
   '열대 분위기의 대형 관엽식물. 반양지·주 1회 물주기.'),
  ('스투키', 18000,
   'https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=600',
   '공기정화 식물. 물을 거의 주지 않아도 잘 자라요.'),
  ('테이블야자', 22000,
   'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=600',
   '책상 위 작은 야자수. 반음지에서도 OK.'),
  ('선인장 세트 (3종)', 15000,
   'https://images.unsplash.com/photo-1509423350716-97f9360b4e09?w=600',
   '미니 선인장 3종 구성. 햇빛 듬뿍, 물은 적게.'),
  ('다육이 모둠 (5종)', 19000,
   'https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=600',
   '귀여운 다육식물 5종. 통풍과 햇빛이 중요해요.'),
  ('유칼립투스 폴리안', 24000,
   'https://images.unsplash.com/photo-1512428813834-c702c7702b78?w=600',
   '은은한 향과 푸른 잎. 밝은 실내 창가에 어울려요.'),
  ('아레카야자', 42000,
   'https://images.unsplash.com/photo-1463320898484-cdee8141c787?w=600',
   '공기정화 1위 식물. 거실 포인트용으로 인기.'),
  ('올리브 나무', 56000,
   'https://images.unsplash.com/photo-1598880940639-81a5d63a3b2f?w=600',
   '지중해 무드 화분. 햇빛 좋은 베란다 추천.'),
  ('필로덴드론 하트립', 21000,
   'https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?w=600',
   '하트 모양 잎의 덩굴식물. 행잉 플랜트로 딱.'),
  ('테라리움 DIY 키트', 29000,
   'https://images.unsplash.com/photo-1466692476655-9e7de0ca275f?w=600',
   '이끼·돌·미니 식물 구성. 직접 꾸미는 유리정원.');
