-- ============================================
-- week-6 shopping_mall_v2 — week-5 Supabase 프로젝트에 추가
-- products는 week-5에서 만든 테이블 그대로 사용 (image_url 컬럼 활용)
-- orders + order_items만 신규
-- ============================================

-- products 시드가 없으면 week-5/shopping_mall/schema.sql 의 INSERT 부분 먼저 실행

-- ── orders ──────────────────────────────────────
drop table if exists public.order_items cascade;
drop table if exists public.orders cascade;

create table public.orders (
  id              bigint primary key generated by default as identity,
  user_id         uuid not null references auth.users(id) on delete cascade,
  total_price     int  not null check (total_price >= 0),
  status          text not null default 'paid',     -- paid / cancelled / shipped
  toss_payment_key text,
  toss_order_id    text unique not null,            -- 토스에 보낸 client orderId
  receiver_email   text,
  paid_at         timestamptz default now(),
  created_at      timestamptz not null default now()
);

alter table public.orders enable row level security;

-- 본인 주문만 조회
drop policy if exists "orders_select_own" on public.orders;
create policy "orders_select_own"
  on public.orders for select to authenticated
  using (user_id = auth.uid());

-- INSERT는 service-role만 (서버에서 결제 승인 후)
drop policy if exists "orders_insert_service" on public.orders;
create policy "orders_insert_service"
  on public.orders for insert to authenticated
  with check (user_id = auth.uid());

-- ── order_items ─────────────────────────────────
create table public.order_items (
  id           bigint primary key generated by default as identity,
  order_id     bigint not null references public.orders(id) on delete cascade,
  product_id   bigint references public.products(id),
  product_name text   not null,
  product_image text,
  quantity     int    not null check (quantity > 0),
  price        int    not null check (price >= 0)
);

alter table public.order_items enable row level security;

drop policy if exists "order_items_select_own" on public.order_items;
create policy "order_items_select_own"
  on public.order_items for select to authenticated
  using (
    exists (
      select 1 from public.orders o
      where o.id = order_id and o.user_id = auth.uid()
    )
  );

drop policy if exists "order_items_insert_own" on public.order_items;
create policy "order_items_insert_own"
  on public.order_items for insert to authenticated
  with check (
    exists (
      select 1 from public.orders o
      where o.id = order_id and o.user_id = auth.uid()
    )
  );

-- ── products INSERT 정책 (관리자만) ─────────────
-- week-5는 INSERT 정책이 없어서 anon은 SELECT만 가능. 관리자가 등록할 때 service-role 사용.
-- (또는 ADMIN_EMAILS 체크는 서버 라우트에서)

-- index
create index if not exists orders_user_id_idx on public.orders(user_id);
create index if not exists order_items_order_id_idx on public.order_items(order_id);
